### ISSUE TITLE
Kubesplit on *List resources without metadata

### ISSUE THREAD

**Issue by brucex** [looztra/kubesplit#5]
* kubesplit version: latest

### Description

Kubesplit marks items that don't have metadata as invalid resources. This is not true for *List resources. We are able to run kubectl apply on configmaplist, rolelist, and rolebindinglist without any issues. Kustomize had a similar issue. https://github.com/kubernetes-sigs/kustomize/issues/688

### What I Did
 
We are using the helmcharts on prometheus operator to get yaml deployment files. 3 of the files include *List resources which don't include metadata but are able to kubectl apply just fine.  Example is here https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/configmap-dashboards.yaml

grafana-dashboardDefinitions.yaml
```
apiVersion: v1
items:
  - apiVersion: v1
    data:
      envoy.json: "some data"
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-statefulset
      namespace: monitoring
  - apiVersion: v1
    data:
      envoy.json: "some data"
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-statefulset2
      namespace: monitoring
kind: ConfigMapList

```

```
kubesplit -i grafana-dashboardDefinitions.yaml -o output
Processing: input=grafana-dashboardDefinitions.yaml, output_dir=output, clean_output_dir=False, typ=rt, explicit_start=True, explicit_end=False, default_flow_style=False, quotes_preserved=True, dash_inwards=True, prefix_resource_files=True
Found [0] valid / [1] invalid / [0] empty resources
```

Since these are valid kubernetes files, i'd at least expect kubesplit to output the unnamed list file somewhere.
