### ISSUE TITLE
Multiline strings generate invalid output when whitespace prefixed data

### ISSUE THREAD

**Issue by warmfusion** [looztra/kubesplit#81]
Multiline yaml entries with whitespace prefixes generate invalid indentation indicators on dump.

## Metadata

* kubesplit version: 0.3.2
* Python version: 3.11.2
* Operating System: Macos / Debian Bullseye

## Description

When splitting configuration files that present with existing multiline data blocks with indentation indicators, the generated split versions have the wrong indicators set.

## What I Did

Given two configmaps in a yaml file named `input.yaml`

```yaml
---
apiVersion: v1
data:
  no_indent_hint: |
    some content here
  no_indent_hint_with_whitespace: |

    some content here
kind: ConfigMap
metadata:
  name: example-no-indicators

---
apiVersion: v1
data:
  indent_2: |2
    some content here

  indent_2_with_whitespace: |2

    some content here
kind: ConfigMap
metadata:
  name: example-with-indicators

```

When processed through kubesplit `❯ kubesplit -i input.yaml -o example`, the generated files for the indicators'

(Shown 'merged' for convenience)
```yaml
---
apiVersion: v1
data:
  no_indent_hint: |
    some content here
  no_indent_hint_with_whitespace: |4

    some content here
kind: ConfigMap
metadata:
  name: example-no-indicators
---
apiVersion: v1
data:
  indent_2: |
    some content here

  indent_2_with_whitespace: |4

    some content here
kind: ConfigMap
metadata:
  name: example-with-indicators
```

Observe how the entries with whitespace prefixed in their data blocks are now indicated with `|4`, even if previously a value of None or 2 was given; this is incorrect, and can be observed with yamllint test;

```
❯ yamllint example/*
example/11--configmap--example-no-indicators.yml
  8:5       error    syntax error: expected <block end>, but found '<scalar>' (syntax)

example/11--configmap--example-with-indicators.yml
  9:5       error    syntax error: expected <block end>, but found '<scalar>' (syntax)
```

## Additional

When using `--no-dash-inwards` argument, the entries are valid, which I belive hints that the problem lies in the yamkix function here;

https://github.com/looztra/yamkix/blob/main/src/yamkix/yamkix.py#L62-L69

Specifically, the 'transform' operationl named [strip_leading_double_space](https://github.com/looztra/yamkix/blob/main/src/yamkix/helpers.py#L25)

**Comment by warmfusion** [comment]
Interestingly, using `ruamel.yaml==0.17.14` results in the `|4` stuff going away, but also the required `|2` values we have in other places also breaks;

eg;
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-example-with-old-ruamel
data:
  example.conf: |2

    configuration text here 
```
becomes

```yaml
...
  example.conf: |

    configuration text here
```
which is wrong too aparently.

**Comment by looztra** [comment]
sorry for the horrible latency.

I had to publish a new version of yamkix that now requires ruamel.yaml>=0.17.27
so I will also have a look at this

(thanks for the detailed report)

**Comment by looztra** [comment]
(to be honest, I'll have to dig into the subject of whitespace prefixed data first, I've never heard of this feature before :smiley_cat: )

**Comment by looztra** [comment]
checked with the updated yamkix version (and ruamel.yaml==0.17.32)

Got

``` yaml
---
apiVersion: v1
data:
  no_indent_hint: |
    some content here
  no_indent_hint_with_whitespace: |2

    some content here
kind: ConfigMap
metadata:
  name: example-no-indicators
---
apiVersion: v1
data:
  indent_2: |
    some content here

  indent_2_with_whitespace: |2

    some content here
kind: ConfigMap
metadata:
  name: example-with-indicators

```

so indicators have the good value, but always output if one of the document has them.
